# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "digital_ocean"

  config.ssh.private_key_path = "#{File.dirname(__FILE__)}/vagrant"
  config.vm.network "public_network"
  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/home/vagrant/tor"
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

  config.vm.provider :digital_ocean do |provider|
    provider.ssh_key_name = "vagrant-key"
    provider.token = "29594fd6f2763c90315c7925c1304154a1a13bd3df36650083afed14f60009ca"
    provider.region = "nyc1"
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -x
    apt-get update
    apt-get install -y vim git automake autoconf make gcc perl libssl-dev openssl zlib1g-dev libevent-dev python-mock # asciidoc
    apt-get install -y libnss3-dev libnss3-dbg
  SHELL
end
